/**
 * TECHMITI'25 Events Database
 * Last Updated: 2023-04-12
 * Version: 1.0.0
 *
 * This file contains the structured data for all events at TECHMITI'25.
 * Each event is categorized by type and includes technical specifications.
 */

const events = [
  {
    id: "EVT-001",
    name: "MAD for CAD",
    category: "Technical",
    subcategory: "Design",
    difficulty: "Intermediate",
    description: `MAD for CAD is an event to showcase your designing skills among hundreds of well-versed participants across Bihar. It is an event of two rounds in which participants have to design products according to the problem statement within a timespan.`,
    technicalDetails: {
      software: ["AutoCAD", "Fusion 360", "SolidWorks", "CATIA"],
      fileFormats: [".dwg", ".dxf", ".step", ".stl"],
      maxFileSize: "50MB",
      rendering: "Required for final submission",
    },
    teamSize: {
      min: 1,
      max: 1,
      recommended: 1,
    },
    date: "12/04/2023",
    time: "09:00 AM - 05:00 PM",
    venue: "CAD Lab, Block A",
    prize: "₹10,000",
    registrationFee: "₹200",
    image: "https://i.imgur.com/vI9i9S5.png",
    ruleBook:
      "https://drive.google.com/file/d/1DX84-QsI1wr_uf8-5WOgZfj55ecee8DE/view?usp=sharing",
    registrationLink: "https://forms.gle/example1",
    icon: "🎨",
    tags: ["CAD", "Design", "Engineering", "3D Modeling"],
    prerequisites: [
      "Basic knowledge of CAD software",
      "Laptop with CAD software installed",
    ],
    judgingCriteria: [
      "Innovation",
      "Technical accuracy",
      "Presentation",
      "Problem-solving",
    ],
    timeline: [
      { time: "09:00 AM", event: "Registration and Check-in" },
      { time: "10:00 AM", event: "Problem Statement Release" },
      { time: "12:00 PM", event: "Mid-evaluation" },
      { time: "04:00 PM", event: "Final Submission" },
      { time: "05:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-002",
    name: "RC Plane",
    category: "Technical",
    subcategory: "Robotics",
    difficulty: "Advanced",
    description: `A radio-controlled aircraft(often called RC aircraft or RC plane) is a small flying machine that is controlled remotely by an operator on the ground using a hand-held radio transmitter. The participants will have to design such RC plane that can fly high under proper control and also, land stable. So, design like wright Brothers, as perfectly aerodynamic as you can and fly high, because the sky is the only limit!`,
    technicalDetails: {
      maxWingspan: "1.5 meters",
      maxWeight: "1 kg",
      powerSource: ["Battery", "Fuel"],
      controlChannels: "Minimum 4 channels",
      materials: ["Balsa wood", "Foam", "Carbon fiber", "Plastic"],
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "10:00 AM - 04:00 PM",
    venue: "Main Ground",
    prize: "₹15,000",
    registrationFee: "₹300",
    image: "https://i.imgur.com/cMCiHQj.png",
    ruleBook:
      "https://drive.google.com/file/d/1woJe0lQSr3dyPqMGE1zWMOFU4VUkubWe/view?usp=sharing",
    registrationLink: "https://forms.gle/example2",
    icon: "✈️",
    tags: ["Aerodynamics", "RC", "Aviation", "Engineering"],
    prerequisites: ["Basic knowledge of aerodynamics", "RC control experience"],
    judgingCriteria: [
      "Flight stability",
      "Design innovation",
      "Control precision",
      "Landing accuracy",
    ],
    timeline: [
      { time: "10:00 AM", event: "Technical Inspection" },
      { time: "11:00 AM", event: "Flight Demonstration" },
      { time: "02:00 PM", event: "Competition Rounds" },
      { time: "04:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-003",
    name: "Dangal",
    category: "Technical",
    subcategory: "Robotics",
    difficulty: "Expert",
    description: `The challenge is to design and build a competent to fight other robots in Battle. The competition is carried out in a tournament format in which the competitors bring their wireless and wired robot ready to battle and pitted against their competitor's robot in one-one matches where the aim is to cause maximum damage or to push the opponents robot off the arena to score maximum points. Team scoring the maximum number of points wins the championship. The challenge is not just the fighting bots but the the hazardous arena which shall contain dead drop ravines, valleys, and other bot damaging structures.`,
    technicalDetails: {
      maxDimensions: "30cm x 30cm x 30cm",
      maxWeight: "15 kg",
      powerSource: "24V DC maximum",
      controlType: ["Wired", "Wireless"],
      weaponTypes: ["Impact", "Lifter", "Spinner", "Hammer"],
    },
    teamSize: {
      min: 3,
      max: 5,
      recommended: 4,
    },
    date: "12/04/2023",
    time: "09:00 AM - 06:00 PM",
    venue: "Robotics Arena, Block B",
    prize: "₹25,000",
    registrationFee: "₹500",
    image: "https://i.imgur.com/DwUVMej.png",
    ruleBook:
      "https://drive.google.com/file/d/1zofTyC8f33A4obDPQXdtP5tfqAYWNOjO/view",
    registrationLink: "https://forms.gle/example3",
    icon: "🤖",
    tags: ["Combat Robotics", "BattleBots", "Engineering", "Mechanics"],
    prerequisites: [
      "Robotics experience",
      "Basic electronics knowledge",
      "Safety training",
    ],
    judgingCriteria: [
      "Damage inflicted",
      "Control precision",
      "Design innovation",
      "Durability",
    ],
    timeline: [
      { time: "09:00 AM", event: "Safety Inspection" },
      { time: "10:00 AM", event: "Preliminary Rounds" },
      { time: "02:00 PM", event: "Quarter Finals" },
      { time: "04:00 PM", event: "Semi Finals" },
      { time: "05:30 PM", event: "Finals" },
      { time: "06:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-004",
    name: "Debug_Thugs",
    category: "Technical",
    subcategory: "Programming",
    difficulty: "Intermediate",
    description: `Debugging is the process of finding and fixing bugs in the source code of any software. This event focuses on problem-solving, critical thinking, and algorithmic thinking of participants alongside their ability to spot errors.`,
    technicalDetails: {
      languages: ["C", "C++", "Java", "Python"],
      platforms: ["Online Judge", "Local IDE"],
      timeLimit: "3 hours",
      problemCount: "5-7",
      difficultyLevels: ["Easy", "Medium", "Hard"],
    },
    teamSize: {
      min: 1,
      max: 1,
      recommended: 1,
    },
    date: "12/04/2023",
    time: "10:00 AM - 01:00 PM",
    venue: "Computer Lab, Block C",
    prize: "₹8,000",
    registrationFee: "₹150",
    image: "https://i.imgur.com/H3zdbIM.png",
    ruleBook:
      "https://drive.google.com/file/d/1mKt3zHgISJFRQxwWBykqEXKw6BggqEPH/view?usp=sharing",
    registrationLink: "https://forms.gle/example4",
    icon: "🐛",
    tags: ["Debugging", "Programming", "Algorithms", "Problem Solving"],
    prerequisites: [
      "Basic programming knowledge",
      "Understanding of data structures",
    ],
    judgingCriteria: [
      "Correctness",
      "Efficiency",
      "Code quality",
      "Time taken",
    ],
    timeline: [
      { time: "10:00 AM", event: "Problem Release" },
      { time: "11:30 AM", event: "Mid-evaluation" },
      { time: "01:00 PM", event: "Final Submission" },
      { time: "02:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-005",
    name: "Line Tracer",
    category: "Technical",
    subcategory: "Robotics",
    difficulty: "Intermediate",
    description: `Teams are required to assemble and form an autonomous bot that can follow a black line over a contrasting surface. The contest aim is to make the bot capable of following a black line on a white background without losing the line in a zig-zag pattern including complex angle turns. The robot must complete the course in the shortest period while maintaining accuracy from starting point to the finish line.`,
    technicalDetails: {
      maxDimensions: "25cm x 15cm x 15cm",
      maxWeight: "1.5 kg",
      sensors: ["IR sensors", "Color sensors"],
      controlType: "Autonomous",
      powerSource: "Battery operated",
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "09:00 AM - 04:00 PM",
    venue: "Robotics Lab, Block B",
    prize: "₹12,000",
    registrationFee: "₹250",
    image: "https://i.imgur.com/bBVdgIO.png",
    ruleBook:
      "https://drive.google.com/file/d/1nnhGz_pkB58DQ0OInPy9-8AFXOUpND7S/view?usp=sharing",
    registrationLink: "https://forms.gle/example5",
    icon: "🚗",
    tags: ["Line Following", "Autonomous", "Robotics", "Sensors"],
    prerequisites: ["Basic electronics", "Programming knowledge"],
    judgingCriteria: ["Speed", "Accuracy", "Design innovation", "Reliability"],
    timeline: [
      { time: "09:00 AM", event: "Technical Inspection" },
      { time: "10:00 AM", event: "Practice Rounds" },
      { time: "12:00 PM", event: "Qualification Rounds" },
      { time: "02:00 PM", event: "Finals" },
      { time: "04:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-006",
    name: "Armstrong",
    category: "Technical",
    subcategory: "Mechanical",
    difficulty: "Advanced",
    description: `Armstrong is an event that tests the power of a hydraulic arm and the knowledge of essential hydraulic components like incompressible liquid, the capacity of fluid, etc. Participants must design a movable hydraulic arm based on a problem statement and perform tasks within a given period.`,
    technicalDetails: {
      maxDimensions: "40cm x 30cm x 30cm",
      maxWeight: "5 kg",
      powerSource: "Manual hydraulic system",
      materials: ["PVC pipes", "Syringes", "Wood", "Metal"],
      fluidType: "Water or oil-based",
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "10:00 AM - 05:00 PM",
    venue: "Mechanical Workshop, Block D",
    prize: "₹15,000",
    registrationFee: "₹300",
    image: "https://i.imgur.com/rNtHqJX.png",
    ruleBook:
      "https://drive.google.com/file/d/1sC4OFU2CcAsNPmb16qWk2ssgW8Me7XRv/view?usp=sharing",
    registrationLink: "https://forms.gle/example6",
    icon: "🦾",
    tags: ["Hydraulics", "Mechanical", "Engineering", "Robotics"],
    prerequisites: ["Basic knowledge of hydraulics", "Mechanical skills"],
    judgingCriteria: [
      "Lifting capacity",
      "Precision",
      "Design innovation",
      "Task completion",
    ],
    timeline: [
      { time: "10:00 AM", event: "Technical Inspection" },
      { time: "11:00 AM", event: "Task Demonstration" },
      { time: "01:00 PM", event: "Competition Rounds" },
      { time: "04:00 PM", event: "Finals" },
      { time: "05:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-007",
    name: "Rube A Cube",
    category: "Technical",
    subcategory: "Puzzle",
    difficulty: "Intermediate",
    description: `The Rube A Cube is a competition consisting of three rounds that challenge participants to solve different types of Rubik's cubes. Each round has its own set of rules, patterns, and tasks that must be completed in order to progress. The competition is not limited to the standard 3x3 Rubik's cube, but also includes other types of cubes like the 2x2, 4x4, Mirror's cube, and Pyraminx cube. The judging criteria are based on how accurately and quickly the participants can complete the tasks for each round.`,
    technicalDetails: {
      cubeTypes: ["2x2", "3x3", "4x4", "Mirror", "Pyraminx"],
      timeLimit: "5 minutes per round",
      rounds: 3,
      scoring: "Time-based with penalties",
      allowedMethods: "Any solving method",
    },
    teamSize: {
      min: 1,
      max: 1,
      recommended: 1,
    },
    date: "12/04/2023",
    time: "11:00 AM - 04:00 PM",
    venue: "Main Hall, Block A",
    prize: "₹7,000",
    registrationFee: "₹150",
    image: "https://i.imgur.com/OwiViSc.png",
    ruleBook:
      "https://drive.google.com/file/d/1q9XzeWqLj_uW0_o3bDcf2zfFxBEXaz50/view?usp=sharing",
    registrationLink: "https://forms.gle/example7",
    icon: "🧩",
    tags: ["Rubik's Cube", "Puzzle", "Speed Solving", "Pattern Recognition"],
    prerequisites: ["Basic cube solving skills"],
    judgingCriteria: [
      "Speed",
      "Accuracy",
      "Pattern recognition",
      "Consistency",
    ],
    timeline: [
      { time: "11:00 AM", event: "Registration" },
      { time: "12:00 PM", event: "Round 1 - 3x3 Cube" },
      { time: "01:30 PM", event: "Round 2 - Special Patterns" },
      { time: "03:00 PM", event: "Round 3 - Multiple Cubes" },
      { time: "04:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-008",
    name: "Frontend Freebirds",
    category: "Technical",
    subcategory: "Web Development",
    difficulty: "Intermediate",
    description: `"Frontend Freebirds" is a web development contest where participants create web pages according to set rules. The contest focuses on front-end design, usability, and accessibility, and winners are selected based on code quality and creativity. It's a chance for developers to showcase their skills and compete for recognition.`,
    technicalDetails: {
      technologies: ["HTML5", "CSS3", "JavaScript", "React", "Vue", "Angular"],
      timeLimit: "4 hours",
      evaluation: "Code review and live demo",
      responsive: "Required for all screen sizes",
      browserSupport: "Latest 2 versions of major browsers",
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "09:00 AM - 01:00 PM",
    venue: "Computer Lab, Block C",
    prize: "₹10,000",
    registrationFee: "₹200",
    image: "https://i.imgur.com/6AaaHI1.png",
    ruleBook:
      "https://drive.google.com/file/d/1cSr3_XuwwSeuBdpg_nbUIcwe8Anfatzn/view?usp=drivesdk",
    registrationLink: "https://forms.gle/example8",
    icon: "💻",
    tags: ["Web Development", "Frontend", "UI/UX", "Responsive Design"],
    prerequisites: [
      "HTML/CSS knowledge",
      "Basic JavaScript",
      "Version control (Git)",
    ],
    judgingCriteria: [
      "Code quality",
      "Design aesthetics",
      "Responsiveness",
      "Performance",
    ],
    timeline: [
      { time: "09:00 AM", event: "Problem Statement Release" },
      { time: "11:00 AM", event: "Mid-evaluation" },
      { time: "01:00 PM", event: "Final Submission" },
      { time: "02:00 PM", event: "Presentations" },
      { time: "03:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-009",
    name: "Hurdle Mania",
    category: "Technical",
    subcategory: "Robotics",
    difficulty: "Advanced",
    description: `The primary objective of this event is to build a racing bot, whether wired or wireless, that can compete against another bot in an arena filled with obstacles such as sharp turns, rough paths, zig-zag paths, and wedges. Participants must complete the course in the shortest possible time during the elimination round to qualify for the final round.`,
    technicalDetails: {
      maxDimensions: "30cm x 20cm x 15cm",
      maxWeight: "3 kg",
      controlType: ["Wired", "Wireless"],
      powerSource: "Battery operated",
      obstacles: ["Sharp turns", "Rough paths", "Zig-zag paths", "Wedges"],
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "10:00 AM - 05:00 PM",
    venue: "Robotics Arena, Block B",
    prize: "₹15,000",
    registrationFee: "₹300",
    image: "https://i.imgur.com/vNdclqR.png",
    ruleBook:
      "https://drive.google.com/file/d/19m1U9Au3Ihvna4nl6bSdQjuEEe3yQEzL/view?usp=sharing",
    registrationLink: "https://forms.gle/example9",
    icon: "🏎️",
    tags: ["Racing", "Robotics", "Obstacle Course", "Engineering"],
    prerequisites: ["Basic electronics", "Mechanical skills"],
    judgingCriteria: [
      "Speed",
      "Obstacle navigation",
      "Design innovation",
      "Reliability",
    ],
    timeline: [
      { time: "10:00 AM", event: "Technical Inspection" },
      { time: "11:00 AM", event: "Practice Rounds" },
      { time: "01:00 PM", event: "Elimination Rounds" },
      { time: "03:00 PM", event: "Finals" },
      { time: "05:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-010",
    name: "Seismic Design",
    category: "Technical",
    subcategory: "Civil",
    difficulty: "Advanced",
    description: `The objective of this competition is to evaluate the team's knowledge of seismic design principles and their ability to apply these principles in a practical context. Participants must consider various factors such as building materials, structural design, and earthquake-resistant technologies to construct a structure that can withstand simulated seismic activity.`,
    technicalDetails: {
      maxDimensions: "50cm x 50cm x 50cm",
      maxWeight: "5 kg",
      materials: ["Balsa wood", "Cardboard", "Straws", "Glue", "Rubber bands"],
      testing: "Simulated seismic activity",
      evaluation: "Structural integrity and design principles",
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "09:00 AM - 04:00 PM",
    venue: "Civil Engineering Lab, Block E",
    prize: "₹12,000",
    registrationFee: "₹250",
    image: "https://i.imgur.com/Jilw8k9.png",
    ruleBook:
      "https://drive.google.com/file/d/10S5BEY0vSIxFrNCxAfxt-W_pJ62rKXn-/view?usp=sharing",
    registrationLink: "https://forms.gle/example10",
    icon: "🏗️",
    tags: [
      "Civil Engineering",
      "Structural Design",
      "Earthquake Resistance",
      "Architecture",
    ],
    prerequisites: [
      "Basic knowledge of structural engineering",
      "Understanding of seismic design principles",
    ],
    judgingCriteria: [
      "Structural integrity",
      "Design innovation",
      "Material efficiency",
      "Seismic resistance",
    ],
    timeline: [
      { time: "09:00 AM", event: "Registration and Check-in" },
      { time: "10:00 AM", event: "Problem Statement Release" },
      { time: "12:00 PM", event: "Mid-evaluation" },
      { time: "03:00 PM", event: "Final Submission" },
      { time: "04:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-011",
    name: "Robosoccer",
    category: "Technical",
    subcategory: "Robotics",
    difficulty: "Advanced",
    description: `ROBOSOCCER is a robotic competition where machines compete against each other in a soccer-like game. Once the game starts, each team's bot is fully autonomous and can be controlled remotely from outside the arena. The objective of the game is to score more goals than the opposing team.
    
    Winning is not only achieved by scoring goals, but also by defending the goal posts against the opponents. The event showcases the perfect combination of coordinated action, communication, and strategy. It challenges participants to develop and apply cutting-edge technologies in robotics, artificial intelligence, and machine learning to create winning strategies.`,
    technicalDetails: {
      maxDimensions: "30cm x 30cm x 30cm",
      maxWeight: "3 kg",
      controlType: "Autonomous with remote override",
      powerSource: "Battery operated",
      sensors: ["IR sensors", "Color sensors", "Ultrasonic sensors"],
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "10:00 AM - 05:00 PM",
    venue: "Robotics Arena, Block B",
    prize: "₹15,000",
    registrationFee: "₹300",
    image: "https://i.imgur.com/HampwTf.png",
    ruleBook:
      "https://drive.google.com/file/d/1tKfi2bhqjVd7xgMiOIZYb_MaxcFOQ_oh/view?usp=sharing",
    registrationLink: "https://forms.gle/example11",
    icon: "⚽",
    tags: ["Robotics", "Soccer", "Autonomous", "AI", "Strategy"],
    prerequisites: [
      "Basic robotics knowledge",
      "Programming skills",
      "Understanding of sensors and control systems",
    ],
    judgingCriteria: [
      "Goal scoring ability",
      "Defensive capabilities",
      "Strategy implementation",
      "Technical innovation",
    ],
    timeline: [
      { time: "10:00 AM", event: "Technical Inspection" },
      { time: "11:00 AM", event: "Practice Rounds" },
      { time: "01:00 PM", event: "Group Stage Matches" },
      { time: "03:00 PM", event: "Semi-finals" },
      { time: "04:30 PM", event: "Finals" },
      { time: "05:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-012",
    name: "Bot A Maze",
    category: "Technical",
    subcategory: "Robotics",
    difficulty: "Intermediate",
    description: `In this event, participants are required to bring bots with or without a handmade chassis and predefined dimensions. The competition will feature a maze with walls of a specified height as obstacles, and the bot must traverse the maze by following any path to minimize the time taken to complete the course.`,
    technicalDetails: {
      maxDimensions: "25cm x 25cm x 25cm",
      maxWeight: "2 kg",
      controlType: ["Autonomous", "Manual"],
      powerSource: "Battery operated",
      sensors: ["IR sensors", "Ultrasonic sensors", "Gyroscope"],
    },
    teamSize: {
      min: 2,
      max: 4,
      recommended: 3,
    },
    date: "12/04/2023",
    time: "09:00 AM - 04:00 PM",
    venue: "Robotics Lab, Block B",
    prize: "₹10,000",
    registrationFee: "₹250",
    image: "https://i.imgur.com/4pr3m4p.png",
    ruleBook:
      "https://drive.google.com/file/d/14wOVge1Nm3H7AUTmSeFH90wW1tA86O0u/view?usp=sharing",
    registrationLink: "https://forms.gle/example12",
    icon: "🧩",
    tags: ["Robotics", "Maze Solving", "Autonomous", "Navigation"],
    prerequisites: [
      "Basic electronics knowledge",
      "Programming skills",
      "Understanding of sensors",
    ],
    judgingCriteria: [
      "Time to complete the maze",
      "Path optimization",
      "Design innovation",
      "Reliability",
    ],
    timeline: [
      { time: "09:00 AM", event: "Technical Inspection" },
      { time: "10:00 AM", event: "Practice Rounds" },
      { time: "12:00 PM", event: "Qualification Rounds" },
      { time: "02:00 PM", event: "Finals" },
      { time: "04:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-013",
    name: "Thrust",
    category: "Technical",
    subcategory: "Aerospace",
    difficulty: "Advanced",
    description: `This event requires basic knowledge of fabrication, materials, and physical calculations involving thrust, air pressure, and other factors that affect a rocket's flight. The competition tests several aspects of the rocket's flight, including range, time of flight, and accuracy of the launching mechanism. Participants must develop and apply scientific principles and engineering concepts to design and build a rocket that can achieve maximum performance and accuracy.`,
    technicalDetails: {
      maxLength: "60 cm",
      maxDiameter: "10 cm",
      maxWeight: "1 kg",
      propulsion: "Water or air pressure",
      materials: ["PVC", "Cardboard", "Plastic", "Lightweight metals"],
    },
    teamSize: {
      min: 2,
      max: 3,
      recommended: 2,
    },
    date: "12/04/2023",
    time: "10:00 AM - 04:00 PM",
    venue: "Main Ground",
    prize: "₹12,000",
    registrationFee: "₹250",
    image: "https://i.imgur.com/xOAa8SO.png",
    ruleBook:
      "https://drive.google.com/file/d/1eLNq6yl8C1itlCJNVNUn-MsPW6Kb7x9q/view",
    registrationLink: "https://forms.gle/example13",
    icon: "🚀",
    tags: ["Aerospace", "Rocketry", "Physics", "Engineering"],
    prerequisites: [
      "Basic knowledge of aerodynamics",
      "Understanding of propulsion systems",
      "Safety awareness",
    ],
    judgingCriteria: [
      "Flight distance",
      "Flight stability",
      "Design innovation",
      "Accuracy of landing",
    ],
    timeline: [
      { time: "10:00 AM", event: "Safety Briefing" },
      { time: "11:00 AM", event: "Technical Inspection" },
      { time: "12:00 PM", event: "Launch Rounds" },
      { time: "03:00 PM", event: "Finals" },
      { time: "04:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-014",
    name: "Hunt & Slay",
    category: "Gaming",
    subcategory: "Battle Royale",
    difficulty: "Intermediate",
    description: `Hunt & Slay is the gaming section of TechMITi, which features a popular BGMI squad tournament. Gamers from around the world who love nothing more than claiming their Chicken Dinner on the virtual battlegrounds of Erangel are invited to compete. Get ready to gear up and take down your opponents in this exciting competition!`,
    technicalDetails: {
      game: "BGMI (Battlegrounds Mobile India)",
      platform: "Mobile",
      format: "Squad (4 players)",
      rounds: "3 matches",
      scoring: "Based on placement and eliminations",
    },
    teamSize: {
      min: 4,
      max: 4,
      recommended: 4,
    },
    date: "12/04/2023",
    time: "11:00 AM - 06:00 PM",
    venue: "Gaming Zone, Block C",
    prize: "₹15,000",
    registrationFee: "₹400",
    image: "https://i.imgur.com/vNbcbla.png",
    ruleBook:
      "https://drive.google.com/file/d/1-scngG3F6w1otLjGlZuNHAeOcrsYUuYp/view?usp=sharing",
    registrationLink: "https://forms.gle/example14",
    icon: "🎮",
    tags: ["Gaming", "BGMI", "Battle Royale", "Esports"],
    prerequisites: [
      "BGMI installed on mobile device",
      "Stable internet connection",
      "Gaming experience",
    ],
    judgingCriteria: [
      "Placement points",
      "Elimination points",
      "Team coordination",
      "Strategy execution",
    ],
    timeline: [
      { time: "11:00 AM", event: "Registration and Check-in" },
      { time: "12:00 PM", event: "Match 1" },
      { time: "02:00 PM", event: "Match 2" },
      { time: "04:00 PM", event: "Match 3" },
      { time: "06:00 PM", event: "Results Announcement" },
    ],
  },
  {
    id: "EVT-015",
    name: "Circuitron",
    category: "Technical",
    subcategory: "Electronics",
    difficulty: "Intermediate",
    description: `CIRCUITRON is a competition that tests participants' knowledge of circuit design using a breadboard and basic analog components such as ICs, diodes, LEDs, capacitors, resistors, and more. Participants will have to create circuits based on a given problem statement and components within a specified time frame.

    The participating teams will be provided with information related to the project they are expected to develop during the competition. All the components required to design the project will be provided, and participants must use their knowledge and skills to create a functional circuit that meets the problem statement requirements.`,
    technicalDetails: {
      components: [
        "ICs",
        "Diodes",
        "LEDs",
        "Capacitors",
        "Resistors",
        "Transistors",
      ],
      tools: ["Breadboard", "Multimeter", "Wire strippers", "Soldering iron"],
      timeLimit: "3 hours",
      powerSource: "DC power supply",
    },
    teamSize: {
      min: 2,
      max: 2,
      recommended: 2,
    },
    date: "12/04/2023",
    time: "09:00 AM - 01:00 PM",
    venue: "Electronics Lab, Block D",
    prize: "₹8,000",
    registrationFee: "₹200",
    image: "https://i.imgur.com/YJS4gQH.png",
    ruleBook:
      "https://drive.google.com/file/d/1h2PdzG7PJCtCPgGwHS9tucOWduaGGGX2/view?usp=sharing",
    registrationLink: "https://forms.gle/example15",
    icon: "⚡",
    tags: ["Electronics", "Circuit Design", "Analog", "Engineering"],
    prerequisites: [
      "Basic electronics knowledge",
      "Understanding of circuit components",
      "Circuit design experience",
    ],
    judgingCriteria: [
      "Circuit functionality",
      "Design efficiency",
      "Component usage",
      "Problem-solving approach",
    ],
    timeline: [
      { time: "09:00 AM", event: "Problem Statement Release" },
      { time: "10:30 AM", event: "Mid-evaluation" },
      { time: "12:30 PM", event: "Final Submission" },
      { time: "01:00 PM", event: "Results Announcement" },
    ],
  },
];

export default events;
