
export const navbarData = [
    {
        id:1,
        title:"Home",
        link:"/"
    },
    {
        id:2,
        title:"Events",
        link:"/events"
    },
    {
        id:3,
        title:"About",
        link:"/about"
    },
    {
        id:4,
        title:"Contact",
        link:"/contact"
    },
    {
        id:5,
        title:"Register",
        link:"/register"
    },
    {
        id:6,
        title:"Gallery",
        link:"/gallery"
    },
    {
        id:7,
        title:"Login",
        link:"/login"
    },
    
]